---
- hosts: Windows_Servers
  gather_facts: false
  collections:
   - microsoft.ad
  
  vars_files:
    - vars.yml
    - passwd.yml

  tasks:
  
   - name: Create Windows Ansible user
     microsoft.ad.win_domain_user:
      name: "{{ item.name }}"
      firstname: "{{item.firstname }}"
      surname: "{{ item.surname }}"
      password: "{{ item.password }}"
      groups: "{{ item.groups|default(omit) }}"
      state: present
      email: '"{{ item.name }}"@{{ domain_name }}'
     with_items: "{{ domainusers }}"
