---
- hosts: Windows_Servers
  gather_facts: false
  
  tasks:

    - name: Disable task event 
      ansible.windows.win_scheduled_task:
        name: Firewall_disable
        path: \
        state: absent

    - name: Reactivating Windows Firewall and Default Rules
      ansible.windows.win_firewall:
        state: enabled
        profiles:
          - Domain
          - Private
          - Public
    
    - name: Re-create the task to monitor Firewall
      win_scheduled_task:
        name: Firewall_disable
        triggers: 
          - type: event
            subscription:  <QueryList><Query Id="0" Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall"><Select Path="Microsoft-Windows-Windows Firewall With Advanced Security/Firewall">*[System[(EventID=2003)]]</Select></Query></QueryList>
        actions:
          - path: C:\Users\Administrator\Documents\callback.bat   
        username: Administrator
        state: present
        tags: create_event
